---
- 

  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Provision instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: hello.ppk
        instance_type: t2.micro
        image: ami-047d7c33f6e7b4bc4
        wait: yes
        count: 1
        region: us-west-1
