---
-
  hosts: cisco_device
  connection: network_cli
  gather_facts: no
  

  tasks:
    - name:  tas
      ios_command:
        commands:
          - show version
      register: output
 
    - name:  deb
      debug:
        var: output

    - name: Create Configs Directory
      file: path=configs state=directory
    
    - name: Generate Cisco Basic Config
      template:
        src:  "templates/loop.j2"
        dest: "configs/{{inventory_hostname}}.cfg"
      delegate_to: localhost

    - name: load Cisco Basic Config
      ios_config:
        src:  "configs/{{inventory_hostname}}.cfg"
        save_when: modified
        
