---
-
  hosts: cisco_device
  connection: network_cli
  
  vars:
    hostname: cisco123
    interfaces:
      - { port: Gigabitethernet0/2, prefix: 10.1.1.0/24 }

  tasks:
   - name: filters
     blockinfile:
       path: /etc/ansible/hosts2
       block: |
         hostname {{ hostname | upper }}
         {% for intf in interfaces %}
         interface {{ intf.port }}
            ip address {{intf.prefix | ipv4(1) | ipv4('address')
               }} {{intf.prefix | ipv4('netmask') }}
         {% endfor %}
     delegate_to: localhost
     
   - name: load Cisco Basic Config
     ios_config:
        src: /etc/ansible/hosts2
        save_when: modified
