---
- hosts: fort_device
  connection: httpapi
  collections:
    - fortinet.fortios

  vars:
    host: "192.168.138.13"
    username: "admin"
    password: "fortigate"
    vdom: "root"
    ssl_verify: "False"

  tasks:
   - name: gather basic system status facts
     fortios_facts:
       host:  "{{ host }}"
       username: "{{ username }}"
       password: "{{ password }}"
       vdom:  "{{ vdom }}"
       gather_subset:
         - fact: 'system_status_select'  
