---
- name: Change hostname on FortiGate
  hosts: fort_device
  connection: httpapi
  gather_facts: no

  collections:
    - fortinet.fortios

  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_network_os: fortinet.fortios
    ansible_httpapi_port: 443
    vdom: "root"  # Specify your VDOM or use "root"

  tasks:
    - name: Set FortiGate hostname
      fortios_system_global:
        vdom: "{{ vdom }}"
        system_global:
          hostname: "New-FortiGate-Hostname"
