---
- hosts: fort_device
  collections:
   - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
  tasks: 
     - name: fetch all firewall addresses
       fortinet.fortios.fortios_configuration_fact:
        selector: firewall_address
       register: output
     - name: debug
       debug:
        var: output
