- hosts: fort_device
  connection: ssh
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: no
   ansible_httpapi_validate_certs: false
   ansible_httpapi_port: 80

  tasks:
   - name: Configure global attributes.
     fortios_system_global:
        vdom:  "{{ vdom }}"
        #access_token: "{{ fortios_access_token }}" #if you prefer access token based authentication, add this line.
        system_global:
            hostname: 'CustomHostName'
