---
- hosts: fort_device
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: true
   ansible_httpapi_validate_certs: false
   ansible_httpapi_port: 443
   ansible_network_os: fortinet.fortios.fortios
  tasks:
   - name: Configure global attributes.
     fortinet.fortios.fortios_system_global:
         system_global:
            admintimeout: "60"
            hostname: 'FGT40F-VPN4'
