---
-
  hosts: juniper_device
  gather_facts: no
  connection: netconf

  tasks:

    - name: Configure subinterfaces first
      junos_config:
        src: subint.j2
        src_format: set

    - name: junipetr system
      junos_interfaces:
        config:
          - name: "{{ item.junos_if }}"
            description: "{{ item.desc }}"
            enabled: "{{ item.enabled }}"
      when: item.unit == 0
      loop: "{{ interfaces }}"
  
      
