---
-
  hosts: juniper_device
  gather_facts: no
  connection: netconf

  tasks:
    - name: junipetr system
      junos_interfaces:
        config:
         - name: em2
           description: second
           enabled: true
           units:
            - name: 0
              description: "This is logical intf unit0"
  
      
