---
-
  hosts: juniper_device
  gather_facts: no
  connection: netconf

  tasks:
    - name: junipetr system
      junos_l3_interfaces:
        config:
         - name: em2
           unit:  0
           ipv4:
            - address: 192.168.1.4
           
      
