---
-
  hosts: juniper
  connection: netconf  


  tasks:

    - name: configure juniper templates
      template:
         src: "templates/junos_bgp.j2"
         dest: "configs/{{inventory_hostname}}.cfg"
      delegate_to: localhost
      

    - name: load Cisco Basic Config
      junos_config:
        src:  "configs/{{inventory_hostname}}.cfg"
        confirm_commit: true
        update: merge

