---
-
  hosts: all
  

  tasks:
    - name: template load
      template:
        src: "templates/cisco_bgp.j2"
        dest: "configs/{{inventory_hostname}}.cfg"
      when: 
         - ansible_network_os == 'ios'  



    - name: load
      ios_config:
        src: "configs/{{inventory_hostname}}.cfg"
        save_when: modified
      when:
         - ansible_network_os == 'ios'



    - name: templates load
      template:
        src: "templates/junos_bgp.j2"
        dest: "configs/{{inventory_hostname}}.cfg"
      when:
         - ansible_network_os == 'junos'




    - name: loads
      junos_config:
        src: "configs/{{inventory_hostname}}.cfg"
        confirm_commit: true
        update: merge
      when:
        - ansible_network_os == 'junos'

