---
-
  hosts: all
  gather_facts: no

  vars_prompt:
    - name: com1
      prompt: enter command1
      private: no

    - name: com2
      prompt: enter command2
      private: no



  tasks:
    - name: execute cisco
      ios_command:
       commands:
         - "{{com1}}"
      register: output
      when: ansible_connection == 'network_cli'

    - name: debug
      debug:
       var: output
      when: ansible_connection == 'network_cli'

    - name: execute juniper
      junos_command:
       commands:
         - "{{com2}}"
      register: output1
      when: ansible_connection == 'netconf'

    - name: debug1
      debug:
       var: output1
      when: ansible_connection == 'netconf'
