---
ansible_host: 192.168.138.10
ansible_user: root
ansible_password: Juniper
ansible_network_os: junipernetworks.junos.junos
ansible_connection: ansible.netcommon.netconf
ansible_port: 22

# Specific variables for the Juniper device
junos_hostname: "juniper12345"

